steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/sawyer-bot', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/sawyer-bot']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'sawyer-bot'
  - '--image'
  - 'gcr.io/$PROJECT_ID/sawyer-bot'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--update-secrets'
  - 'TELEGRAM_BOT_TOKEN=telegram_bot_token:latest'
  - '--service-account'
  - 'cloud-run-sa@sawyer-bot.iam.gserviceaccount.com'

